### ISSUE TITLE
When Big and die the texture is glitchy!

### ISSUE THREAD

**Issue by jonabird** [gamemash/platformer#17]
When I play the game. I have collected a mushroom and jumped in a hole and died. Then the game tries to make a dead animation with big Mario and Mario texture bugs. Small Mario's normal die texture with half crouching big Mario on head.

I hope I explained that well.

I would like to help but I do not know where to start ):

**Comment by oponder** [comment]
Thanks for reporting! When starting out, reporting bugs is already very helpful :D 

This bug is in a part that has to do with rendering and the way the graphics are loaded probably.

I'm not sure I can look into it now into the exact cause right now though.

Have you tried to run it locally for yourself, so you can see what happens when you edit parts of the code?

You need to have `nodejs`, `npm` and `budo`. Then you can run `make develop` and any changes you make in the code should be visible.

That way you can play around a bit and see what parts of the code have impact on the game.

For example this file is pretty interesting: https://github.com/gamemash/platformer/blob/master/src/mario.js#L15

It has all the rules for how mario moves. You could make him faster or jump higher.

**Comment by jonabird** [comment]
OK.
Thanks!
I have started looking in the Code already. `make develop` works well. @teemow helped me.
I start looking at the problem :)
